# Site settings
title: Mike Czarny, Systems and Network Engineer 
description: About Mike Czarny

# User settings
username: Mike Czarny
user_description: Originally from Poland, now living in LA (not limited to), I am a systems and network engineer with a passion for building and automating (and all the fun stuff in between). Some would call this DevOps/SysOps/NetOps/SRE. I've had some success in both startup and corporate enviroments having worn many hats during a seven years career. My focus has recently shifted from traditional cloud and bare-metal services to blockchain technology and cryptocurrency, which I see as the next disruptive layers of the internet, and an area that I'm most excited about contributing to.     
user_title: Tinkerer. Hacker. Engineer.  
email: mike@r3lik.com
github_username: r3lik
twitter_username:  r3lik
linkedin_username: mike-czarny

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src', 'node_modules']


